name: Firebase - Staging

on:
  pull_request:

env:
  FIREBASE_CHANNEL_ID:  "pr-${{github.event.number}}"
  FIREBASE_PROJECT_ID: mm-static-site-staging
  FIREBASE_SERVICE_ACCOUNT: "${{ secrets.STAGING_FIREBASE_SERVICE_ACCOUNT }}"

jobs:
  staging-build-test-deploy:
    name: Staging - Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Get cached dependencies
        uses: actions/cache@v2
        id: cache-node-modules
        with:
          path: |
            node_modules
            functions/node_modules
          key: node-modules-${{ hashFiles('**/yarn.lock') }}

      - if: steps.cache-node-modules.outputs.cache-hit != 'true'
        name: Install dependencies
        run: yarn install

      - name: Run unit tests
        run: yarn test:unit

      - name: Run accessibility tests
        run: yarn test:a11y

      - name: Build
        env:
          GATSBY_URL: https://${{ env.FIREBASE_PROJECT_ID }}--${{ env.FIREBASE_CHANNEL_ID }}.web.app
        run:  yarn build

      - name: Deploy Firebase preview channel
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ env.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 7d
          projectId: "${{ env.FIREBASE_PROJECT_ID }}"
          channelId: "${{ env.FIREBASE_CHANNEL_ID }}"
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.FIREBASE_PROJECT_ID }}
          service_account_key: ${{ env.FIREBASE_SERVICE_ACCOUNT }}
          export_default_credentials: true

      - name: Deploy all other Firebase resources
        run: yarn firebase deploy --except hosting --project ${{ env.FIREBASE_PROJECT_ID }}
