name: Linting

on:
  push:
  pull_request:

jobs:
  cache-keys:
    name: Setup – Cache keys
    runs-on: ubuntu-latest

    outputs:
      build: build-${{ steps.build.outputs.hash }}-v2
      dot-cache: dot-cache-${{ github.event.number }}-v1
      node-modules: node-modules-${{ steps.node-modules.outputs.hash }}-v1

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: build
        run: echo "::set-output name=hash::${{ hashFiles('assets/**', 'content/**', 'layouts/**', 'static/**', '**/package.json', '**/package-lock.json') }}"

      - id: node-modules
        run: echo "::set-output name=hash::${{ hashFiles('**/package-lock.json') }}"

  test-lint:
    name: Test – Lint
    needs: cache-keys
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Get cached dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ${{ needs.cache-keys.outputs.node-modules }}

      - name: Install dependencies
        run: npm install

      - name: Run linters
        run: npm run lint
